Fixes fastify/help#442
fastify/example pull request #17
Opened 2021-05-30 17:39 UTC by luisorbaiceta

Refactored code to new property validatorCompiler

2021-05-30 21:42 UTC, mcollina approved these changes
lgtm

2021-05-31 08:31 UTC, mcollina requested changes
The version in package.json must be updated as well https://github.com/fastify/example/blob/master/validation-messages/package.json#L19

2021-05-31 09:23 UTC, luisorbaiceta commented
> The version in package.json must be updated as well https://github.com/fastify/example/blob/master/validation-messages/package.json#L19

Done. I have also updated tap version due to found vulnerabilities

2021-05-31 10:37 UTC, mcollina commented on validation-messages/package.json
> +    "fastify": ">=3.0.0",
```suggestion
    "fastify": "^3.0.0",
```

2021-05-31 10:37 UTC, mcollina approved these changes
lgtm

2021-05-31 10:37 UTC, merged